@startuml

'state events

[*] --> authenfication
authenfication -> [*] : wrong credentials
authenfication --> WebApp : successful authentication

state WebApp {

[*] --> restart_device
restart_device --> progress_state
progress_state ---> [*] : success
progress_state --> error : fails
error --> [*]

[*] --> database_section

database_section --> update_database
update_database --> [*]
database_section --> view_database
view_database -> view_database : loop

}

'state descriptions
authenfication : authenfication over active directory
restart_device : user is able to select a POE powered device 
restart_device : and restart it over the port on the allocated switch
progress_state : shows the current progress
error : restart action didn't work
database_section : state only for admins
database_section : - Able to edit and look at the diagrams
view_database : shows all tables
view_database : filter options included
update_database : admin is able to change data

@enduml