@startuml

'styles and configs for diagram
skinparam actorStyle awesome
left to right direction

'users/actors
actor user as user
actor admin as root

'use-cases
rectangle Switch-Port-Reboot-WebApp {

database "lidl devices" as db_ld

usecase "update database" as ud
usecase "preview database" as pd

usecase "reboot device" as rd
usecase "search device" as sd
usecase "login" as l

usecase "push button" as pb
usecase "select spinner" as ss
usecase "select database data" as sdd
usecase "keyboard input" as ki
usecase "import file" as if

}

database "active directory" as ad

'relations
user --> rd
user --> sd
user <|- root : "inerhits"
user --> l

root --> ud
root --> pd

sd ..> db_ld : "get data"
sd --> ki : "requires function"
sd --> ss : "requires function"

rd --> pb : "requires function"

pd ..> db_ld : "get data"

ud .> db_ld : "add/delete data"
ud --> if : "requires function"
ud --> sdd : "requires function"

l .> ad : authentication

@enduml